INSERT INTO cities (name, provinceid) VALUES
('Thành phố Long Xuyên', 1), ('Thành phố Châu Đốc', 1),
('Thành phố Vũng Tàu', 2), ('Thành phố Bà Rịa', 2),
('Thành phố Bắc Giang', 3), ('Huyện Lục Ngạn', 3),
('Thành phố Bắc Kạn', 4), ('Huyện Chợ Đồn', 4),
('Thành phố Bạc Liêu', 5), ('Thị xẫ Giá Rai', 5),
('Thành phố Bắc Ninh', 6), ('Thành phố Từ Sơn', 6),
('Thành phố Bến Tre', 7), ('Huyện Châu Thành', 7),
('Thành phố Quy Nhơn', 8), ('Thị xã An Nhơn', 8),
('Thành phố Thủ Dầu Một', 9), ('Thành phố Bến Cát', 9),
('Thành phố Đồng Xoài', 10), ('Thị xã Phước Long', 10),
('Thành phố Phan Thiết', 11), ('Thị xã La Gi', 11),
('Thành phố Cà Mau', 12), ('Huyện Năm Căn', 12),
('Thành phố Cần Thơ', 13),
('Thành phố Cao Bằng', 14), ('Huyện Trùng Khánh', 14),
('Thành phố Đà Nẵng', 15),
('Thành phố Buôn Ma Thuột', 16), ('Thị xã Buôn Hồ', 16),
('Thành phố Gia Nghĩa', 17), ('Huyện Đắk Mil', 17),
('Thành phố Điện Biên Phủ', 18), ('Thị xã Mường Lay', 18),
('Thành phố Biên Hòa', 19), ('Thành phố Long Khánh', 19),
('Thành phố Cao Lãnh', 20), ('Thành phố Sa Đéc', 20),
('Thành phố Pleiku', 21), ('Thị xã An Khê', 21),
('Thành phố Hà Giang', 22), ('Huyện Đồng Văn', 22),
('Thành phố Phủ Lý', 23), ('Thị xã Duy Tiên', 23),
('Thành phố Hà Nội', 24),
('Thành phố Hà Tĩnh', 25), ('Thị xã Hồng Lĩnh', 25),
('Thành phố Hải Dương', 26), ('Thành phố Chí Linh', 26),
('Thành phố Hải Phòng', 27),
('Thành phố Vị Thanh', 28), ('Thành phố Ngã Bảy', 28),
('Thành phố Hòa Bình', 29), ('Huyện Mai Châu', 29),
('Thành phố Hưng Yên', 30), ('Thị xã Mỹ Hào', 30),
('Thành phố Nha Trang', 31), ('Thành phố Cam Ranh', 31),
('Thành phố Rạch Giá', 32), ('Thành phố Hà Tiên', 32),
('Thành phố Kon Tum', 33), ('Huyện Ngọc Hồi', 33),
('Thành phố Lai Châu', 34), ('Huyện Tam Đường', 34),
('Thành phố Đà Lạt', 35), ('Thành phố Bảo Lộc', 35),
('Thành phố Lạng Sơn', 36), ('Huyện Văn Lãng', 36),
('Thành phố Lào Cai', 37), ('Thị xã Sa Pa', 37),
('Thành phố Tân An', 38), ('Thị xã Kiến Tường', 38),
('Thành phố Nam Định', 39), ('Huyện Nghĩa Hưng', 39),
('Thành phố Vinh', 40), ('Thị xã Cửa Lò', 40),
('Thành phố Ninh Bình', 41), ('Thành phố Tam Điệp', 41),
('Thành phố Phan Rang-Tháp Chàm', 42), ('Huyện Ninh Sơn', 42),
('Thành phố Việt Trì', 43), ('Thị xã Phú Thọ', 43),
('Thành phố Tuy Hòa', 44), ('Thị xã Sông Cầu', 44),
('Thành phố Đồng Hới', 45), ('Thị xã Ba Đồn', 45),
('Thành phố Tam Kỳ', 46), ('Thành phố Hội An', 46),
('Thành phố Quảng Ngãi', 47), ('Thị xã Đức Phổ', 47),
('Thành phố Hạ Long', 48), ('Thành phố Cẩm Phả', 48),
('Thành phố Đông Hà', 49), ('Thị xã Quảng Trị', 49),
('Thành phố Sóc Trăng', 50), ('Thị xã Vĩnh Châu', 50),
('Thành phố Sơn La', 51), ('Huyện Mộc Châu', 51),
('Thành phố Tây Ninh', 52), ('Thị xã Hòa Thành', 52),
('Thành phố Thái Bình', 53), ('Huyện Tiền Hải', 53),
('Thành phố Thái Nguyên', 54), ('Thành phố Sông Công', 54),
('Thành phố Thanh Hóa', 55), ('Thành phố Sầm Sơn', 55),
('Thành phố Huế', 56), ('Huyện Quảng Điền', 56),
('Thành phố Mỹ Tho', 57), ('Thành phố Gò Công', 57),
('Thành phố Hồ Chí Minh', 58),
('Thành phố Trà Vinh', 59), ('Huyện Duyên Hải', 59),
('Thành phố Tuyên Quang', 60), ('Huyện Na Hang', 60),
('Thành phố Vĩnh Long', 61), ('Thị xã Bình Minh', 61),
('Thành phố Vĩnh Yên', 62), ('Thành phố Phúc Yên', 62),
('Thành phố Yên Bái', 63), ('Thị xã Nghĩa Lộ', 63);