INSERT INTO dow (name,cityid) VALUE
('Phường Bình Đức',1),('Phường Mỹ Đình',1),
('Phường Vĩnh Mỹ',2),('Xã Vĩnh Tế',2),
('Phường Thắng Tam',3),('Phường Nguyễn An Ninh',3),
('Phường Phước Hưng',4),('Phường Long Toàn',4),
('Phường Thọ Xương',5),('Phường Trần Nguyên Hãn',5),
('Thị Trấn Chũ',6),('Xã Tân Sơn',6),
('Phường Nguyễn Thị Minh Khai',7),('Phường Phùng Chí Kiên',7),
('Xã Xuân Lạc',8),('Thị Trấn Bằng Lũng',8),
('Phường 1',9),('Phường Nhà Mát',9),
('Phường Hộ Phòng',10),('Xã Phong Thạnh Đông',10),
('Phường Vũ Ninh',11),('Phường Đáp Cầu',11),
('Phường Đông Ngàn',12),('Phường Tam Sơn',12),
('Phường Phú Tân',13),('Phường Phú Khương',13),
('Thị trấn Châu Thành',14),('Xã Tân Thạch',14),
('Phường Nhơn Bình',15),('Phường Đống Đa',15),
('Phường Đập Đá',16),('Xã Nhơn Mỹ',16),
('Phường Hiệp Thành',17),('Phường Phú Lợi',17),
('Phường Chánh Phú Hòa',18),('Phường An Điền',18),
('Phường Tân Phú',19),('Phường Tân Xuân',19),
('Phường Thác Mơ',20),('Phường Long Thủy',20),
('Phường Mũi Né',21),('Phường Hàm Tiến',21),
('Phường Phước Hội',22),('Phường Phước Lộc',22),
('Phường 9',23),('Phường 4',23),
('Thị trấn Năm Căn',24),('Xã Hàm Rồng',24),
('Quận Ninh Kiều',25),('Quận Ô Môn',25),
('Phường Sông Hiến',26),('Phường Ngọc Xuân',26),
('Thị trấn Trà Lĩnh',27),('Xã Cô Mười',27),
('Phường Hòa Hiệp Bắc',28),('Phường Hòa Minh',28),
('Phường Tân Lập',29),('Phường Tân Hòa',29),
('Phường An Lạc',30),('Phường Đạy Hiếu',30),
('Phường Nghĩa Đức',31),('Phường Nghĩa Thành',31),
('Thị trấn Đắk Mil',32),('Xã Đắk Lao',32),
('Phường Noong Bua',33),('Phường Him Lam',33),
('Xã Lay Nưa',34),('Phường Sông Đà',34),
('Phường Trảng Dài',35),('Phường Tây Phong',35),
('Phường Xuân Trung',36),('Phường Xuân Bình',36),
('Phường 11',37),('Xã Mỹ Ngãi',37),
('Xã Tân Khánh Đông',38),('Phường Tân Quy Đông',38),
('Phường Yên Đỗ',39),('Phường Ia Kring',39),
('Phường An Bình',40),('Xã Tú An',40),
('Phường Quang Trung',41),('Phường Ngọc Hà',41),
('Thị trấn Phó Bảng',42),('Xã Lũng Cú',42),
('Phường Lương Khánh Thiện',43),('Phường Lê Hồng Phong',43),
('Phường Đồng Văn',44),('Xã Mộc Bắc',44),
('Quận Ba Đình',45),('Quận Hoàn Kiếm',45),
('Phường Trần Phú',46),('Phường Nam Hà',46),
('Phường Bắc Hồng',47),('Phường Nam Hồng',47),
('Phường Cẩm Thượng',48),('Phường Nguyễn Trãi',48),
('Phường Phả Lại',49),('Phường Sao Đỏ',49),
('Quận Hồng Bàng',50),('Quận Đồ Sơn',50),
('Phường I',51),('Xã Hoả Lựu',51),
('Phường Ngã Bảy',52),('Phường Lái Hiếu',52),
('Phường Thái Bình',53),('Phường Hữu Nghị',53),
('Xã Tân Thành',54),('Thị trấn Mai Châu',54),
('Phường Lam Sơn',55),('Phường Hiến Nam',55),
('Phường Bần Yên Nhân',56),('Phường Phan Đình Phùng',56),
('Phường Vĩnh Hòa',57),('Phường Vĩnh Hải',57),
('Phường Cam Nghĩa',58),('Phường Ba Ngòi',58),
('Phường Vĩnh Thanh Vân',59),('Phường Vĩnh Thanh',59),
('Phường Tô Châu',60),('Phường Đông Hồ',60),
('Phường Quyết Thắng',61),('Phường Ngô Mây',61),
('Thị trấn Plei Kần',62),('Xã Sa Loong',62),
('Phường Quyết Thắng',63),('Xã Sùng Phài',63),
('Thị trấn Phong Thổ',64),('Thị trấn Tam Đường',64),
('Xã Tà Nung',65),('Phường 12',65),
('Phường Lộc Phát',66),('Xã Đạm Bri',66),
('Phường Hoàng Văn Thụ',67),('Phường Vĩnh Trại',67),
('Xã Trùng Khánh',68),('Thị trấn Na Sầm',68),
('Phường Duyên Hải',69),('Phường Lào Cai',69),
('Phường Sa Pả',70),('Phường Ô Quý Hồ',70),
('Phường Tân Khánh',71),('Xã Hướng Thọ Phú',71),
('Xã Thạnh Trị',72),('Xã Bình Tân',72),
('Phường Trần Tế Xương',73),('Phường Vị Hoàng',73),
('Thị trấn Liễu Đề',74),('Xã Nghĩa Đồng',74),
('Phường Hà Huy Tập',75),('Phường Quán Bàu',75),
('Phường Nghi Thuỷ',76),('Phường Nghi Hương',76),
('Phường Đông Thành',77),('Phường Nam Thành',77),
('Phường Bắc Sơn',78),('Xã Yên Sơn',78),
('Phường Đô Vinh',79),('Phường Thanh Sơn',79),
('Xã Lương Sơn',80),('Thị trấn Tân Sơn',80),
('Phường Dữu Lâu',81),('Phường Tiên Cát',81),
('Phường Trường Thịnh',82),('Phường Hùng Vương',82),
('Phường 1',83),('Phường Phú Thạnh',83),
('Phường Xuân Phú',84),('Xã Xuân Lâm',84),
('Phường Hải Thành',85),('Phường Đông Phú',85),
('Phường Ba Đồn',86),('Phường Quảng Long',86),
('Phường Tân Thạnh',87),('Phường Phước Hòa',87),
('Phường Minh An',88),('Phường Tân An',88),
('Phường Lê Hồng Phong',89),('Phường Trần Phú',89),
('Phường Nguyễn Nghiêm',90),('Xẫ Phổ An',90),
('Phường Hà Khánh',91),('Phường Hà Phong',91),
('Phường Cửa Ông',92),('Phường Mông Dương',92),
('Phường Đông Giang',93),('Phường Đông Lễ',93),
('Phường An Đôn',94),('Phường 2',94),
('Phường 5',95),('Phường 7',95),
('Phường Khánh Hòa',96),('Xã Hòa Đông',96),
('Phường Tô Hiệu',97),('Phường Quyết Thắng',97),
('Thị trấn Mộc Châu',98),('Xã Tân Lập',98),
('Phường Hiệp Ninh',99),('Phường 1',99),
('Phường Long Hoa',100),('Phường Hiệp Tân',100),
('Phường Lê Hồng Phong',101),('Phường Bồ Xuyên',101),
('Thị trấn Tiền Hải',102),('Xã Đông Hải',102),
('Phường Quang Vinh',103),('Phường Hoàng Văn Thụ',103),
('Phường Lương Sơn',104),('Phường Châu Sơn',104),
('Phường Hàm Rồng',105),('Phường Đông Thọ',105),
('Phường Trung Sơn',106),('Phường Bắc Sơn',106),
('Phường Phú Nhuận',107),('Phường Phú Bình',107),
('Xã Quảng Thái',108),('Thị trấn Sịa',108),
('Phường Tân Long',109),('Phường 5',109),
('Phường 3',110),('Phường 2',110),
('Quận Bình Tân',111),('Quận Bình Thạnh',111),
('Xã Long Đức',112),('Phường 9',112),
('Xã Đôn Xuân',113),('Xã Đôn Châu',113),
('Phường Phan Thiết',114),('Phường Minh Xuân',114),
('Thị trấn Na Hang',115),('Xã Thúy Loa',115),
('Phường 9',116),('Phường 5',116),
('Phương Cái Vồn',117),('Phường Thanh Phước',117),
('Phường Tích Sơn',118),('Phường Liên Bảo',118),
('Phường Trưng Trắc',119),('Phường Trung Nhị',119),
('Phường Yên Thịnh',120),('Phường Yên Ninh',120),
('Phường Pú Trạng',121),('Phường Trung Tâm',121);
